spring:
  jpa:
    generate-ddl=false:
    hibernate:
      ddl-auto=create-drop:h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
clientes:
  autenticacion: &{AUTETICACION_API_URL}