spring:
  application:
    name: 'sentenciados_ms'
  profiles:
    active: 'loc'
# Para exponer actuador de Spring Boot
management:
  info:
    env:
      enabled: true
    git:
      enable: true
      mode: full

  endpoints:
    web:
      exposure:
        include: "health,info"
info:
  application:
    name: ${spring.application.name}