spring:
  application:
    name: '@project.name@'
  liquibase:
    change-log: 'classpath:db/databaseChangeLog.yaml'
    enabled: false

# Para exponer actuador de Spring Boot
management:
  info:
    env:
      enabled: true
    git:
      enable: true
      mode: simple

  endpoints:
    web:
      exposure:
        include: "health,info"

info:
  application:
    name: ${spring.application.name}
    description: '@project.description@'