spring:
  jpa:
    generate-ddl=false:
    hibernate:
      ddl-auto=create-drop:h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: postgres
    url: { SET_YOUR_ORIGIN }
    username:  {SET_YOUR_USERNAME}
    password:  {SET_YOUR_SECRET_PASSWORD}
    driverClassName: org.postgresql.Driver
clientes:
  autenticacion: { SET_YOUR_AUTENTICATION_API_URL }